#!/usr/bin/env python3

import colors as c
import time

count_length = 0.387 


while True:
    c.clear_screen()

for verse in range(5):

for badger in range(11):
     print(c.yellow + 'Badger!' + c.reset)
     time.sleep(count_length)

for mushroom in range(2):
     print(c.magenta + 'Mushroom.' + c.reset)
     time.sleep(count_length * 2)

c.clear_screen()





